name: custom_cursor_example
description: Demonstrates how to use the custom_cursor plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  custom_cursor:
    path: ../
  lucide_icons: ^0.94.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  custom_cursor_macos:
    path: ../../custom_cursor_macos
  custom_cursor_platform_interface:
    path: ../../custom_cursor_platform_interface

flutter:
  uses-material-design: true
  assets:
    - assets/crosshair.png