name: custom_cursor
description: Flutter plugin for creating custom cursors on desktop platforms
homepage: https://github.com/BringingFire/custom_cursor/tree/dev/custom_cursor
repository: https://github.com/BringingFire/custom_cursor/tree/dev/custom_cursor
version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  custom_cursor_macos: ^1.0.0
  custom_cursor_platform_interface: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        default_package: custom_cursor_macos
